---
- name: "End the play for hosts that do not run CentOS or RHEL"
  meta: end_host
  when:
  - ansible_distribution != 'CentOS' and ansible_distribution != 'RedHat' 

- name: "Make sure the network interface exists on the host"
  fail: 
    msg: "The specified network (network.conn_name: {{ network.conn_name }}) does not exist"
  when: not network.conn_name in ansible_interfaces
