---
- name: "Gather facts to get the new variables"
  gather_facts:
  delegate_to: "{{ hostname.value | default(inventory_hostname) }}"

- name: "Fail if the IP has not been set correctly"
  fail:
    msg: "Something went wrong!! The IP is not what you set!!"
  delegate_to: "{{ hostname.value | default(inventory_hostname) }}"
  when: ansible_default_ipv4.address != network.ip4

- name: "Print instructions to ssh into new host"
  debug:
    msg: >
      You can now SSH into {{ ansible_nodename }} with:
      ssh {{ ansible_nodename }}
  delegate_to: "{{ hostname.value | default(inventory_hostname) }}"
