---
- name: "Preflight Checks"
  include_tasks: 00-preflight-checks.yml

- name: "Install Dependencies"
  include_tasks: 01-dependencies.yml

- name: "Set Static IP"
  include_tasks: 02-set-static-ip.yml

- name: "Set hostname"
  include_tasks: 03-set-hostname.yml
  when: hostname.set

- name: "Add the new host to the inventory"
  include_tasks: 04-add-host.yml

- name: "Consistency Checks"
  include_tasks: 99-verification.yml
